apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashuwebapp
  name: ashuwebapp # name of deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashuwebapp
  strategy: {}
  template: # template section 
    metadata:
      creationTimestamp: null
      labels:
        app: ashuwebapp
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        ports:
        - containerPort: 80
        env: # calling variables 
        - name: WORDPRESS_DB_HOST 
          value: ashudblb1 # name of service of Db deployment 
        - name: WORDPRESS_DB_PASSWORD # root password 
          valueFrom:
            secretKeyRef:
              name: db-cred
              key: rootpw 
        resources: {}
status: {}
